#ifndef POCKETSTATION_AUDIO_H
#define POCKETSTATION_AUDIO_H

#pragma once

/* Generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque Opus encoder handle. Created once per session; not thread-safe.
 * The iOS caller must not share this pointer across threads.
 */
typedef struct PksOpusEncoder PksOpusEncoder;

/**
 * Create an Opus encoder.
 *
 * sample_rate: must be 48000 (Opus operates internally at 48 kHz; any other
 *              value returns null — this is a hard rejection, not silent rounding).
 * channels:    1 (mono) or 2 (stereo). Any other value returns null.
 * bitrate_kbps: target bitrate in kbps (e.g. 64). 0 = Opus auto (VBR).
 *
 * Returns null on invalid parameters or on internal encoder failure.
 *
 * # Safety
 * The returned pointer must be destroyed with `pks_opus_encoder_destroy`.
 */
struct PksOpusEncoder *pks_opus_encoder_create(unsigned int sample_rate,
                                               uint8_t channels,
                                               unsigned int bitrate_kbps);

/**
 * Destroy an encoder created by pks_opus_encoder_create.
 * Safe to call with null.
 *
 * # Safety
 * `enc` must be a pointer returned by `pks_opus_encoder_create` or null.
 */
void pks_opus_encoder_destroy(struct PksOpusEncoder *enc);

/**
 * Update the bitrate of a running encoder. Called on CODEC_HINT relay messages (AUDIO-021).
 *
 * enc:          pointer from pks_opus_encoder_create. No-op if null (returns -1).
 * bitrate_kbps: new target bitrate in kbps (e.g. 32, 64, 96). 0 = Opus auto (VBR).
 *
 * Returns 0 on success, -1 if enc is null, -2 on internal Opus error.
 *
 * # Safety
 * `enc` must be a valid pointer from `pks_opus_encoder_create` or null.
 */
int pks_opus_encoder_set_bitrate(struct PksOpusEncoder *enc, unsigned int bitrate_kbps);

/**
 * Encode one PCM frame to Opus.
 *
 * pcm:          f32 interleaved samples, 48 kHz (960 samples for 20ms mono).
 * sample_count: number of f32 samples (960 for 20ms mono).
 * out_buf:      caller-allocated output buffer.
 * out_cap:      capacity of out_buf in bytes (256 is sufficient for any Opus frame).
 *
 * Returns:  number of bytes written on success.
 *           -1 if enc is null.
 *           -2 on encoding error.
 *
 * # Safety
 * - `enc` must be a valid pointer from `pks_opus_encoder_create` or null.
 * - `pcm` must point to at least `sample_count` valid f32 values.
 * - `out_buf` must point to at least `out_cap` bytes of writable memory.
 */
int pks_encode_opus(struct PksOpusEncoder *enc,
                    const float *pcm,
                    uintptr_t sample_count,
                    unsigned char *out_buf,
                    uintptr_t out_cap);

#endif  /* POCKETSTATION_AUDIO_H */
