#ifndef POCKETSTATION_AUDIO_H
#define POCKETSTATION_AUDIO_H

#pragma once

/* Generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque Opus encoder handle. Created once per session; not thread-safe.
 * The iOS caller must not share this pointer across threads.
 */
typedef struct PsOpusEncoder PsOpusEncoder;

/**
 * Create an Opus encoder.
 * sample_rate: must be 48000. channels: 1 (mono) or 2 (stereo).
 * bitrate_kbps: target bitrate in kbps (e.g. 64).
 * Returns null on failure.
 *
 * # Safety
 * The returned pointer must be destroyed with `ps_opus_encoder_destroy`.
 */
struct PsOpusEncoder *ps_opus_encoder_create(unsigned int _sample_rate,
                                             uint8_t _channels,
                                             unsigned int _bitrate_kbps);

/**
 * Destroy an encoder created by ps_opus_encoder_create.
 * Safe to call with null.
 *
 * # Safety
 * `enc` must be a pointer returned by `ps_opus_encoder_create` or null.
 */
void ps_opus_encoder_destroy(struct PsOpusEncoder *enc);

/**
 * Encode one PCM frame to Opus.
 *
 * pcm:          f32 interleaved samples, 48 kHz (960 samples for 20ms mono).
 * sample_count: number of f32 samples (960 for 20ms mono).
 * out_buf:      caller-allocated output buffer.
 * out_cap:      capacity of out_buf in bytes (256 is sufficient for any Opus frame).
 *
 * Returns:  number of bytes written on success.
 *           -1 if enc is null.
 *           -2 on encoding error.
 *
 * # Safety
 * - `enc` must be a valid pointer from `ps_opus_encoder_create` or null.
 * - `pcm` must point to at least `sample_count` valid f32 values.
 * - `out_buf` must point to at least `out_cap` bytes of writable memory.
 */
int ps_encode_opus(struct PsOpusEncoder *enc,
                   const float *pcm,
                   uintptr_t sample_count,
                   unsigned char *out_buf,
                   uintptr_t out_cap);

#endif  /* POCKETSTATION_AUDIO_H */
