[package]
name = "pocketstation-graph"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pocketstation-frame = { path = "../pocketstation-frame", version = "0.1.0" }
pocketstation-bus = { path = "../pocketstation-bus", version = "0.1.0" }
